### ISSUE TITLE
更新待办还是报错

### ISSUE THREAD

**Issue by niulinlnc** [007gzs/dingtalk-sdk#29]
File "xx\python\lib\site-packages\dingtalk\client\base.py", line 130, in _handle_result
    if ('success' in top_result and not top_result['success']) or (
TypeError: argument of type 'bool' is not iterable

**Comment by 007gzs** [comment]
master 试下

**Comment by niulinlnc** [comment]
就是拉的最新master测试的

**Comment by 007gzs** [comment]
我发的时候刚更新的master

**Comment by niulinlnc** [comment]
还是报错

**Comment by niulinlnc** [comment]
代办更新有生效

**Comment by 007gzs** [comment]
报错位置发下

**Comment by niulinlnc** [comment]
完整的报错是这样的
注：odoo是一个开源erp框架。
Odoo Server Error
Traceback (most recent call last):
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\odoo\odoo12EE\source\odoo\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\odoo\odoo12EE\source\odoo\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "D:\odoo\odoo12EE\source\odoo\odoo\http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "d:\odoo\odoo12ee\source\odoo\addons\web\controllers\main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "d:\odoo\odoo12ee\source\odoo\addons\web\controllers\main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "D:\odoo\odoo12EE\source\odoo\odoo\api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "D:\odoo\odoo12EE\source\odoo\odoo\api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "d:\odoo\odoo12ee\source\odoo-dingtalk\dindin_workrecord\models\work_record.py", line 210, in record_update
    client.workrecord.update(userid, record_id)
  File "D:\odoo\odoo12EE\runtime\python\lib\site-packages\dingtalk\client\api\workrecord.py", line 51, in update
    {"userid": userid, "record_id": record_id}
  File "D:\odoo\odoo12EE\runtime\python\lib\site-packages\dingtalk\client\api\base.py", line 26, in _top_request
    return self._client.top_request(method, params, format_, v, simplify, partner_id, url, **kwargs)
  File "D:\odoo\odoo12EE\runtime\python\lib\site-packages\dingtalk\client\base.py", line 216, in top_request
    try:
  File "D:\odoo\odoo12EE\runtime\python\lib\site-packages\dingtalk\client\base.py", line 83, in _request
    res, method, url, result_processor, top_response_key, **kwargs
  File "D:\odoo\odoo12EE\runtime\python\lib\site-packages\dingtalk\client\base.py", line 130, in _handle_result
    if isinstance(top_result, dict):
TypeError: argument of type 'bool' is not iterable

**Comment by niulinlnc** [comment]
top_result  输出值是 True

**Comment by niulinlnc** [comment]
self._handle_result输出是：
{'errcode': 0, 'access_token': '7fef3c18fb9437c08a4cc7e18ee9c690', 'errmsg': 'ok', 'expires_in': 7200}
好像把"result":true 弄丢了。

**Comment by 007gzs** [comment]
提交master了，测下

**Comment by niulinlnc** [comment]
ok了
